#if 0
This file was generated by mkexternalsh on Thu Mar  3 17:22:35 CET 2011.
Do not edit.
#endif

#if NOUNDERSCORE

#define cachelookup ljcachelookup

#else

#define cachelookup_ ljcachelookup_

#endif
